import assert from 'node:assert/strict'
import { createServer } from 'node:http'
import test from 'node:test'
import { registerKnowledgeWeb } from '../lib/web.js'
import { plainTextFromDocument, plainTextToDocument } from '../lib/web-note-editor.js'

test('plain text note documents preserve logical lines exactly', () => {
  const source = '第一行\n会自动折行但仍是一行的长内容\n\n最后一行\n'
  assert.equal(plainTextFromDocument(plainTextToDocument(source)), source)
})

test('management console serves a secured same-origin application', async (t) => {
  let route
  const ctx = {
    webServer: {
      register(value) {
        route = value
        return () => { route = undefined }
      },
    },
    get() { return undefined },
  }
  const dispose = registerKnowledgeWeb(ctx, '/knowledge', '/knowledge-local/v1', 'same-origin', 'desktop-embed-token')
  assert.equal(route.kind, 'prefix')
  assert.equal(route.path, '/knowledge')
  const server = createServer((req, res) => void route.handler(req, res))
  await new Promise(resolve => server.listen(0, '127.0.0.1', resolve))
  const address = server.address()
  const base = `http://127.0.0.1:${address.port}`
  t.after(async () => {
    dispose()
    await new Promise(resolve => server.close(resolve))
  })

  const index = await fetch(`${base}/knowledge`)
  assert.equal(index.status, 200)
  assert.equal(index.headers.get('x-frame-options'), 'SAMEORIGIN')
  assert.match(index.headers.get('content-security-policy'), /frame-ancestors 'self'/)
  assert.match(index.headers.get('content-security-policy'), /img-src 'self' data: blob:/)
  assert.match(index.headers.get('content-security-policy'), /frame-src blob:/)
  const html = await index.text()
  assert.match(html, /name="dsh-knowledge-api" content="\/knowledge-local\/v1"/)
  assert.match(html, /name="dsh-knowledge-auth-mode" content="same-origin"/)
  assert.match(html, /src="\/knowledge\/app\.js\?v=[a-f0-9]{12}"/)
  assert.match(html, /src="\/knowledge\/change-review\.js\?v=[a-f0-9]{12}"/)
  assert.match(html, /src="\/knowledge\/markdown-preview\.js\?v=[a-f0-9]{12}"/)
  assert.match(html, /src="\/knowledge\/workspace-effects\.js\?v=[a-f0-9]{12}"/)
  assert.match(html, /name="dsh-knowledge-asset-version" content="[a-f0-9]{12}"/)
  assert.match(html, /href="\/knowledge\/styles\.css\?v=[a-f0-9]{12}"/)
  assert.equal(index.headers.get('cache-control'), 'no-store')

  const script = await fetch(`${base}/knowledge/app.js`)
  assert.equal(script.status, 200)
  assert.match(script.headers.get('content-type'), /text\/javascript/)
  assert.equal(script.headers.get('cache-control'), 'public, max-age=31536000, immutable')
  const application = await script.text()
  assert.match(application, /sessionStorage/)
  assert.match(application, /document-index/)
  assert.doesNotMatch(application, /api\('documents'\)/)
  assert.match(application, /note-workspace/)
  assert.match(application, /note-tree-panel/)
  assert.match(application, /note-tree-base/)
  assert.match(application, /note-tree-document/)
  assert.match(application, /data-knowledge-motion-key/)
  assert.match(application, /knowledge-library:\$\{base\.id\}/)
  assert.match(application, /knowledge-mount:\$\{targetKind\}:\$\{base\.id\}/)
  assert.match(application, /data-document-id/)
  assert.match(application, /DshKnowledgeEffects/)
  assert.match(application, /note-editor/)
  assert.match(application, /note-title-input/)
  assert.match(application, /knowledge-live-editor/)
  assert.match(application, /DshKnowledgeMarkdown\.renderMarkdown/)
  assert.match(application, /markdown-table-scroll/)
  assert.match(application, /表格内容，可横向滚动/)
  assert.match(application, /loadMarkdownNoteEditor/)
  assert.match(application, /DshKnowledgeNoteEditor/)
  assert.match(application, /createPlainTextEditor/)
  assert.match(application, /function binaryUploadRequest\(/)
  assert.match(application, /request\.upload\.addEventListener\('progress'/)
  assert.match(application, /function collectNoteEntry\(/)
  assert.match(application, /function importNotePlans\(/)
  assert.doesNotMatch(application, /DshKnowledgePlainTextEditor|plain-text-editor\.js/)
  assert.doesNotMatch(application, /function switchDocumentMode\(/)
  const editableNoteSource = application.slice(application.indexOf('function renderEditableNote('), application.indexOf('function renderNoteDocumentBreadcrumb('))
  assert.doesNotMatch(editableNoteSource, /note-mode-switch|预览.*编辑|renderMarkdownPreview/)
  assert.doesNotMatch(editableNoteSource, /notes-document-paper|notes-document-editor|textarea/)
  assert.match(editableNoteSource, /notes-document-title/)
  assert.match(editableNoteSource, /spellcheck: 'false'/)
  assert.match(editableNoteSource, /has-line-numbers/)
  assert.match(editableNoteSource, /notes-plain-editor/)
  assert.match(editableNoteSource, /mountPlainTextNoteEditor/)
  assert.doesNotMatch(editableNoteSource, /class: 'notes-plain-editor', contenteditable/)
  assert.match(editableNoteSource, /saveEditableNoteTitle/)
  assert.match(editableNoteSource, /body: \{ name \}/)
  assert.match(application, /data-tree-open/)
  assert.match(application, /note-tree-scrim/)
  assert.match(application, /saveDocumentEditor/)
  assert.match(application, /createBlankDocument/)
  assert.match(application, /function documentKnowledgeBases/)
  assert.match(application, /function openKnowledgeBaseDocuments/)
  assert.match(application, /function renderKnowledgeBaseDetail/)
  assert.match(application, /params\.append\('knowledgeBaseId'/)
  assert.match(application, /libraryDetail/)
  assert.doesNotMatch(application, /inspectedKnowledgeBaseId/)
  assert.match(application, /mounts\/resolve/)
  assert.match(application, /未挂载到当前会话/)
  assert.match(application, /confirmDeleteDocument/)
  assert.match(application, /openFinalizeDocument/)
  assert.match(application, /reopenDocument/)
  assert.match(application, /已收集完成/)
  assert.match(application, /editor-save-status/)
  assert.doesNotMatch(application, /renderDocumentModeTabs|renderLegacyEntries/)
  assert.match(application, /app-sidebar-resizer/)
  assert.doesNotMatch(application, /视图设置|openLayoutEditor|layoutRangeField/)
  assert.match(application, /pane-toggle-button/)
  assert.match(application, /aria-pressed/)
  assert.match(application, /workspace-switcher/)
  assert.match(application, /knowledgeBaseQuery/)
  assert.match(application, /function renderNotes\(\)/)
  assert.match(application, /function loadDocumentPage/)
  assert.match(application, /function loadDocumentSearch/)
  assert.match(application, /继续加载/)
  assert.match(application, /function uploadNoteFiles\(files, parentId\)/)
  assert.match(application, /function importDroppedNotes\(dataTransfer, parentId\)/)
  assert.match(application, /function readNoteDirectoryEntries\(entry\)/)
  assert.match(application, /webkitGetAsEntry/)
  assert.match(application, /function openDocumentNoteReferencePicker/)
  assert.match(application, /function renderDocumentReferenceBar/)
  assert.match(application, /document-reference-bar/)
  assert.match(application, /entries\/\$\{encodeURIComponent\(editor\.id\)\}\/note-references/)
  const knowledgeEditorSource = application.slice(application.indexOf('function renderNoteEditor('), application.indexOf('function renderMarkdownPreview('))
  assert.doesNotMatch(knowledgeEditorSource, /insertMarkdown\(reference\)|@ 引用笔记/)
  assert.match(application, /function clearNoteDragState/)
  assert.match(application, /function installNoteDragRecovery/)
  assert.doesNotMatch(application, /dataTransfer\.types\.includes/)
  assert.match(application, /note:\/\//)
  assert.match(application, /复制引用/)
  assert.match(application, /function renderNoteFileToolbar\(node, options = \{\}\)/)
  assert.match(application, /node\.editable/)
  assert.match(application, /function releaseNoteAsset\(\)/)
  assert.doesNotMatch(application, /openNoteFilePreview/)
  assert.match(application, /writebackPolicy/)
  assert.match(application, /openGlobalWritebackModelEditor/)
  assert.match(application, /严谨/)
  assert.match(application, /主动/)
  assert.match(application, /loading-skeleton/)
  assert.match(application, /function renderCandidateDiff/)
  assert.match(application, /function renderDiffLine/)
  assert.match(application, /DshKnowledgeReview\.createReviewChange/)
  assert.match(application, /写入新文档/)
  assert.match(application, /合并到文档/)
  assert.match(application, /确认合并/)
  assert.match(application, /data-sidebar-hidden/)
  assert.match(application, /function applySidebarVisibility\(shell, hidden\)/)
  assert.match(application, /const sidebarUnavailable = compact \? !state\.menuOpen : hidden/)
  assert.match(application, /sidebar\?\.toggleAttribute\('inert', sidebarUnavailable\)/)
  assert.match(application, /main\?\.toggleAttribute\('inert', compact && state\.menuOpen\)/)
  assert.match(application, /class: 'app-sidebar-scrim'/)
  assert.match(application, /toggle\.setAttribute\('aria-pressed', String\(visible\)\)/)
  const sidebarToggleSource = application.slice(application.indexOf('function setSidebarHidden('), application.indexOf('function renderSidebar('))
  assert.doesNotMatch(sidebarToggleSource, /renderShell\(\)/)
  assert.match(application, /永久删除/)
  assert.match(application, /输入知识库名称确认/)
  assert.match(application, /x-dsh-knowledge-client/)
  assert.match(application, /远程知识库 API/)
  assert.match(application, /复制地址/)
  assert.match(application, /开启远程 API/)
  assert.match(application, /已撤销令牌已永久删除/)
  assert.match(application, /captureScrollPosition/)
  assert.match(application, /restoreScrollPosition/)
  assert.match(application, /data-scroll-key/)
  assert.match(application, /host-theme-ready/)
  assert.match(application, /event\.source !== window\.parent/)
  assert.match(application, /parentOrigin && event\.origin !== parentOrigin/)
  assert.match(application, /CSS\.supports\('color'/)
  assert.match(application, /root\.style\.colorScheme/)
  assert.match(application, /root\.dataset\.colorScheme/)
  assert.match(application, /installHostThemeBridge\(\)\.then\(\(\) => boot\(\)\)/)

  const effectsScript = await fetch(`${base}/knowledge/workspace-effects.js`)
  assert.equal(effectsScript.status, 200)
  const effects = await effectsScript.text()
  assert.match(effects, /DshKnowledgeEffects/)
  assert.match(effects, /IntersectionObserver/)
  assert.match(effects, /ResizeObserver/)
  assert.match(effects, /feDisplacementMap/)
  assert.doesNotMatch(effects, /feColorMatrix|feBlend/)
  assert.match(effects, /knowledge-glass-filter/)
  assert.match(effects, /knowledge-border-surface/)
  assert.match(effects, /knowledge-card-surface/)
  assert.match(effects, /knowledge-glare-surface/)
  assert.match(effects, /prefers-reduced-transparency/)

  const stylesheet = await fetch(`${base}/knowledge/styles.css`)
  assert.equal(stylesheet.status, 200)
  const styles = await stylesheet.text()
  assert.match(styles, /data-sidebar-hidden="true"/)
  assert.match(styles, /\.app-sidebar-scrim \{ position: fixed; inset: 0; z-index: 30; display: block;/)
  assert.match(styles, /\.sidebar \{ position: fixed;[^}]*z-index: 40;/)
  assert.doesNotMatch(styles, /data-menu-open="true"\]::after/)
  assert.match(styles, /\.note-workspace/)
  assert.match(styles, /\.note-tree-panel \{[\s\S]*min-height: 0;[\s\S]*height: 100%;[\s\S]*overflow: hidden;/)
  assert.match(styles, /\.note-tree \{[\s\S]*overflow-y: auto;/)
  assert.match(styles, /\.note-editor \{[\s\S]*height: 100%;[\s\S]*overflow: hidden;/)
  assert.match(styles, /\.note-editor-toolbar \{[\s\S]*z-index: 2;[\s\S]*background: var\(--material-toolbar\);/)
  assert.match(styles, /\.note-editor-scroll \{[\s\S]*overflow: auto;[\s\S]*overscroll-behavior: contain;/)
  assert.match(styles, /\.tree-folder-icon \{[\s\S]*mask: url\("data:image\/svg\+xml/)
  assert.match(styles, /\.note-tree-group\[data-expanded="true"\] \.tree-folder-icon/)
  assert.match(styles, /\.tree-document-icon \{[\s\S]*mask: url\("data:image\/svg\+xml/)
  assert.match(styles, /\.note-tree-document\[aria-current="page"\] \.tree-document-icon/)
  assert.match(styles, /\.markdown-preview/)
  assert.match(styles, /\.markdown-table-scroll \{[\s\S]*overflow-x: auto/)
  assert.match(styles, /\.note-editor \{[\s\S]*container-name: note-editor;[\s\S]*container-type: inline-size;/)
  assert.match(styles, /\.note-editor-actions \{[\s\S]*flex-wrap: wrap;/)
  assert.match(styles, /@container note-editor \(max-width: 700px\)/)
  assert.match(styles, /@container note-editor \(max-width: 480px\)/)
  assert.match(styles, /\.document-finalized-banner/)
  assert.match(styles, /container-type: inline-size/)
  assert.match(styles, /note-workspace\[data-tree-open="true"\]/)
  assert.match(styles, /background: color-mix\(in srgb, var\(--dialog-surface\) 88%, transparent\)/)
  assert.match(styles, /\.input, \.select \{ height: 38px/)
  assert.match(styles, /scrollbar-color: var\(--scrollbar-thumb\) transparent/)
  assert.match(styles, /--material-panel: color-mix\(in srgb, var\(--surface-raised\) 82%, transparent\)/)
  assert.match(styles, /--accent: #3a3a3c/)
  assert.match(styles, /--glass-filter: saturate\(1\.18\) contrast\(1\.025\) blur\(28px\)/)
  assert.match(styles, /@media \(prefers-color-scheme: dark\)[\s\S]*:root:not\(\[data-color-scheme\]\)/)
  assert.match(styles, /:root\[data-color-scheme="dark"\]/)
  assert.match(styles, /:root\[data-dsh-host-theme="true"\] body \{ background: transparent; \}/)
  assert.match(styles, /\.knowledge-card-surface \{/)
  assert.match(styles, /\.knowledge-glass-surface\[data-knowledge-glass="svg"\]/)
  assert.match(styles, /\.knowledge-border-surface::before/)
  assert.match(styles, /\.knowledge-glare-surface::after/)
  assert.match(styles, /\.knowledge-list-reveal\.is-visible/)
  assert.match(styles, /\.knowledge-list-reveal \{[\s\S]*translate: 0 16px;[\s\S]*scale: \.97;/)
  assert.match(styles, /\.base-grid \.knowledge-list-reveal \{[\s\S]*translate: 0 20px;[\s\S]*scale: \.96;/)
  assert.match(effects, /\.base-grid/)
  assert.match(effects, /\.mount-table/)
  assert.match(effects, /knowledgeListLayout/)
  assert.match(effects, /remove\("is-visible"\)/)
  assert.doesNotMatch(effects, /unobserve/)
  assert.match(styles, /\.knowledge-animated-list\[data-scroll-top="false"\]\[data-scroll-bottom="false"\]/)
  assert.match(styles, /@media \(prefers-reduced-transparency: reduce\)/)
  assert.match(styles, /input\[type="checkbox"\],[\s\S]*appearance: none;/)
  assert.match(styles, /input\[type="checkbox"\]:checked,[\s\S]*background: var\(--accent\)/)
  assert.match(styles, /\.select \{[\s\S]*appearance: none;[\s\S]*background-image:/)
  assert.match(styles, /\.range-row input\[type="range"\]::-webkit-slider-thumb/)
  assert.match(styles, /\.archived-bases summary::-webkit-details-marker/)
  assert.match(styles, /grid-template-columns: subgrid/)
  assert.match(styles, /\.library-detail-header/)
  assert.match(styles, /\.candidate-change/)
  assert.match(styles, /\.diff-viewer \{[^}]*overscroll-behavior: auto;/)
  assert.match(styles, /\.notes-workspace/)
  assert.match(styles, /\.app-shell \{[\s\S]*height: 100dvh;[\s\S]*overflow: hidden;/)
  assert.match(styles, /\.app-shell \{[\s\S]*transition: grid-template-columns 230ms var\(--ease-out\);/)
  assert.match(styles, /\.sidebar \{[\s\S]*border-radius: 20px;[\s\S]*overflow: hidden;/)
  assert.match(styles, /data-sidebar-hidden="true"\][^}]*> \.sidebar \{[\s\S]*opacity: 0;[\s\S]*translateX/)
  assert.doesNotMatch(styles, /data-sidebar-hidden="true"[^}]*\{[^}]*display: none/)
  assert.match(styles, /\.nav \{[\s\S]*overflow-x: hidden;[\s\S]*overflow-y: auto;[\s\S]*scrollbar-gutter: stable;/)
  assert.doesNotMatch(styles, /\.nav-button:hover \{[^}]*translateX/)
  assert.match(styles, /\.topbar \{[\s\S]*border-radius: 18px;[\s\S]*overflow: hidden;/)
  assert.match(styles, /\.main \{[\s\S]*height: 100dvh;[\s\S]*overflow-y: auto;/)
  assert.match(styles, /\.app-shell\[data-view="notes"\] \.view-stage \{[\s\S]*height: 100%;[\s\S]*overflow: hidden;/)
  assert.match(styles, /--font-reading:/)
  assert.match(styles, /\.markdown-preview \{[\s\S]*font: 16px\/1\.55 var\(--font-reading\);/)
  assert.match(styles, /\.notes-tree-branch\[role="group"\]/)
  assert.match(styles, /\.notes-tree-chevron::before/)
  assert.match(styles, /\.notes-file-info/)
  assert.match(styles, /\.notes-live-editor-surface/)
  assert.match(styles, /\.knowledge-live-editor/)
  assert.doesNotMatch(styles, /\.note-mode-switch/)
  assert.doesNotMatch(styles, /\.notes-document-paper/)
  assert.doesNotMatch(styles, /\.notes-document-editor/)
  assert.match(styles, /\.notes-document-title/)
  assert.match(styles, /\.notes-document-title:focus,[\s\S]*box-shadow: none;/)
  assert.match(styles, /\.notes-plain-editor \{[\s\S]*background: transparent;/)
  assert.match(styles, /\.notes-plain-editor-surface \{[\s\S]*counter-reset: note-line;[\s\S]*cursor: text;/)
  assert.match(styles, /\.notes-plain-editor-surface > p::before \{[\s\S]*content: counter\(note-line\);[\s\S]*user-select: none;/)
  assert.doesNotMatch(styles, /\.notes-plain-editor \.cm-/)
  assert.match(styles, /\.notes-content\.is-document\.has-line-numbers \{[\s\S]*--notes-document-inline:/)
  assert.match(styles, /\.notes-content\.is-document \{[\s\S]*display: block;/)
  assert.match(styles, /\.notes-tree-branch \{[\s\S]*grid-template-columns: minmax\(0, 1fr\);/)
  assert.match(styles, /\.notes-tree-node \{[\s\S]*min-width: 0;[\s\S]*max-width: 100%;/)
  assert.match(styles, /\.notes-tree-row \{[\s\S]*overflow: hidden;/)
  assert.match(styles, /\.notes-tree-name \{[\s\S]*text-overflow: ellipsis;/)
  assert.match(styles, /\.notes-tree-item:hover \.notes-tree-row,[\s\S]*padding-right: calc\(var\(--notes-row-actions-width\) \+ 7px\);/)
  assert.match(styles, /\.notes-live-editor-surface:focus,[\s\S]*box-shadow: none;/)
  assert.match(styles, /\.notes-inline-viewer/)
  assert.match(styles, /\.note-reference/)
  assert.match(styles, /\.document-reference-bar/)
  assert.match(styles, /\.document-reference-list \{[\s\S]*overflow-x: auto/)
  assert.match(styles, /\.notes-drop-overlay/)
  assert.match(styles, /\.notes-transfer-track/)
  assert.match(styles, /transform: scaleX\(var\(--notes-transfer-progress\)\)/)
  assert.match(styles, /\.notes-transfer\[data-state="scanning"\] \.notes-transfer-fill/)
  assert.match(styles, /\.diff-line\.is-add/)
  assert.match(styles, /\.diff-line\.is-remove/)
  assert.match(styles, /\.diff-viewer/)
  assert.doesNotMatch(styles, /candidate-comparison/)
  assert.match(styles, /\[data-base-detail="true"\]/)
  const shellSource = application.slice(application.indexOf('function renderShell()'), application.indexOf('function renderSidebar()'))
  assert.doesNotMatch(shellSource, /新建知识库|新建知识/)
  const sidebarSource = application.slice(application.indexOf('function renderSidebar()'), application.indexOf('function renderCurrentView()'))
  assert.match(sidebarSource, /知识工作区/)
  assert.match(sidebarSource, /笔记工作区/)
  assert.match(sidebarSource, /知识库与挂载/)
  assert.doesNotMatch(sidebarSource, /interfaceIcon|nav-icon/)
  const documentsSource = application.slice(application.indexOf('function renderEntries()'), application.indexOf('function renderCandidates()'))
  assert.match(documentsSource, /note-tree-search/)
  assert.match(documentsSource, /新建文档/)
  assert.doesNotMatch(documentsSource, /条目管理/)
  const knowledgeBaseCardSource = application.slice(application.indexOf('function renderKnowledgeBaseCard('), application.indexOf('function findExplicitMount('))
  assert.match(knowledgeBaseCardSource, /查看知识/)
  assert.match(knowledgeBaseCardSource, /openKnowledgeBaseDocuments/)
  assert.doesNotMatch(knowledgeBaseCardSource, /navigate\('entries'\)/)
  assert.match(application, /function openSheet/)
  assert.match(styles, /dialog\.sheet/)

  const markdownPreview = await fetch(`${base}/knowledge/markdown-preview.js`)
  assert.equal(markdownPreview.status, 200)
  assert.match(markdownPreview.headers.get('content-type'), /text\/javascript/)
  assert.equal(markdownPreview.headers.get('cache-control'), 'public, max-age=31536000, immutable')
  assert.match(await markdownPreview.text(), /DshKnowledgeMarkdown/)

  const noteEditor = await fetch(`${base}/knowledge/note-editor.js`)
  assert.equal(noteEditor.status, 200)
  assert.match(noteEditor.headers.get('content-type'), /text\/javascript/)
  assert.equal(noteEditor.headers.get('cache-control'), 'public, max-age=31536000, immutable')
  const noteEditorSource = await noteEditor.text()
  assert.match(noteEditorSource, /DshKnowledgeNoteEditor/)
  assert.match(noteEditorSource, /spellcheck:"false"/)

  const plainTextEditor = await fetch(`${base}/knowledge/plain-text-editor.js`)
  assert.equal(plainTextEditor.status, 404)

  const changeReview = await fetch(`${base}/knowledge/change-review.js`)
  assert.equal(changeReview.status, 200)
  assert.match(changeReview.headers.get('content-type'), /text\/javascript/)
  assert.equal(changeReview.headers.get('cache-control'), 'public, max-age=31536000, immutable')
  assert.match(await changeReview.text(), /DshKnowledgeReview/)

  const embedded = await fetch(`${base}/knowledge?embed=desktop-embed-token`)
  assert.equal(embedded.status, 200)
  assert.equal(embedded.headers.get('x-frame-options'), null)
  assert.doesNotMatch(embedded.headers.get('content-security-policy'), /frame-ancestors/)

  const invalidEmbed = await fetch(`${base}/knowledge?embed=wrong-token`)
  assert.equal(invalidEmbed.status, 200)
  assert.equal(invalidEmbed.headers.get('x-frame-options'), 'SAMEORIGIN')
  assert.match(invalidEmbed.headers.get('content-security-policy'), /frame-ancestors 'self'/)

  const missing = await fetch(`${base}/knowledge/not-found.js`)
  assert.equal(missing.status, 404)
  const post = await fetch(`${base}/knowledge`, { method: 'POST' })
  assert.equal(post.status, 405)
})
